// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: file_reader.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileReader_ReadFile_FullMethodName     = "/FileReader/ReadFile"
	FileReader_ReadNewLine_FullMethodName  = "/FileReader/ReadNewLine"
	FileReader_ReadFileFull_FullMethodName = "/FileReader/ReadFileFull"
)

// FileReaderClient is the client API for FileReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileReaderClient interface {
	ReadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (FileReader_ReadFileClient, error)
	ReadNewLine(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*ReadReply, error)
	ReadFileFull(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*ReadReply, error)
}

type fileReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewFileReaderClient(cc grpc.ClientConnInterface) FileReaderClient {
	return &fileReaderClient{cc}
}

func (c *fileReaderClient) ReadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (FileReader_ReadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileReader_ServiceDesc.Streams[0], FileReader_ReadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fileReaderReadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileReader_ReadFileClient interface {
	Recv() (*ReadReply, error)
	grpc.ClientStream
}

type fileReaderReadFileClient struct {
	grpc.ClientStream
}

func (x *fileReaderReadFileClient) Recv() (*ReadReply, error) {
	m := new(ReadReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileReaderClient) ReadNewLine(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*ReadReply, error) {
	out := new(ReadReply)
	err := c.cc.Invoke(ctx, FileReader_ReadNewLine_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileReaderClient) ReadFileFull(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*ReadReply, error) {
	out := new(ReadReply)
	err := c.cc.Invoke(ctx, FileReader_ReadFileFull_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileReaderServer is the server API for FileReader service.
// All implementations must embed UnimplementedFileReaderServer
// for forward compatibility
type FileReaderServer interface {
	ReadFile(*FileRequest, FileReader_ReadFileServer) error
	ReadNewLine(context.Context, *FileRequest) (*ReadReply, error)
	ReadFileFull(context.Context, *FileRequest) (*ReadReply, error)
	mustEmbedUnimplementedFileReaderServer()
}

// UnimplementedFileReaderServer must be embedded to have forward compatible implementations.
type UnimplementedFileReaderServer struct {
}

func (UnimplementedFileReaderServer) ReadFile(*FileRequest, FileReader_ReadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedFileReaderServer) ReadNewLine(context.Context, *FileRequest) (*ReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadNewLine not implemented")
}
func (UnimplementedFileReaderServer) ReadFileFull(context.Context, *FileRequest) (*ReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFileFull not implemented")
}
func (UnimplementedFileReaderServer) mustEmbedUnimplementedFileReaderServer() {}

// UnsafeFileReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileReaderServer will
// result in compilation errors.
type UnsafeFileReaderServer interface {
	mustEmbedUnimplementedFileReaderServer()
}

func RegisterFileReaderServer(s grpc.ServiceRegistrar, srv FileReaderServer) {
	s.RegisterService(&FileReader_ServiceDesc, srv)
}

func _FileReader_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileReaderServer).ReadFile(m, &fileReaderReadFileServer{stream})
}

type FileReader_ReadFileServer interface {
	Send(*ReadReply) error
	grpc.ServerStream
}

type fileReaderReadFileServer struct {
	grpc.ServerStream
}

func (x *fileReaderReadFileServer) Send(m *ReadReply) error {
	return x.ServerStream.SendMsg(m)
}

func _FileReader_ReadNewLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileReaderServer).ReadNewLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileReader_ReadNewLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileReaderServer).ReadNewLine(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileReader_ReadFileFull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileReaderServer).ReadFileFull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileReader_ReadFileFull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileReaderServer).ReadFileFull(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileReader_ServiceDesc is the grpc.ServiceDesc for FileReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FileReader",
	HandlerType: (*FileReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadNewLine",
			Handler:    _FileReader_ReadNewLine_Handler,
		},
		{
			MethodName: "ReadFileFull",
			Handler:    _FileReader_ReadFileFull_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFile",
			Handler:       _FileReader_ReadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "file_reader.proto",
}
