name: Docker Build, Push Images and Canary Test,

on:
  push:
    branches:
      - add-ci-component

env:
  RELEASE: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker images
        run: |
          cd docker-hadoop
          
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pash-base:${{ env.RELEASE }} ./pash-base --build-arg RELEASE=${{ env.RELEASE }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hadoop-namenode:${{ env.RELEASE }} ./namenode --build-arg RELEASE=${{ env.RELEASE }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pash-base:${{ env.RELEASE }} ./pash-base --build-arg RELEASE=${{ env.RELEASE }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hadoop-pash-base:${{ env.RELEASE }} ./base --build-arg RELEASE=${{ env.RELEASE }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hadoop-namenode:${{ env.RELEASE }} ./namenode --build-arg RELEASE=${{ env.RELEASE }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hadoop-datanode:${{ env.RELEASE }} ./datanode --build-arg RELEASE=${{ env.RELEASE }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hadoop-resourcemanager:${{ env.RELEASE }} ./resourcemanager --build-arg RELEASE=${{ env.RELEASE }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hadoop-nodemanager:${{ env.RELEASE }} ./nodemanager --build-arg RELEASE=${{ env.RELEASE }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hadoop-historyserver:${{ env.RELEASE }} ./historyserver --build-arg RELEASE=${{ env.RELEASE }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hadoop-submit:${{ env.RELEASE }} ./submit --build-arg RELEASE=${{ env.RELEASE }}
  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pash-base:${{ env.RELEASE }}
          docker push ${{ secrets.DOCKER_USERNAME }}/hadoop-namenode:${{ env.RELEASE }}
          docker push ${{ secrets.DOCKER_USERNAME }}/pash-base:${{ env.RELEASE }} 
          docker push ${{ secrets.DOCKER_USERNAME }}/hadoop-pash-base:${{ env.RELEASE }}
          docker push ${{ secrets.DOCKER_USERNAME }}/hadoop-namenode:${{ env.RELEASE }} 
          docker push ${{ secrets.DOCKER_USERNAME }}/hadoop-datanode:${{ env.RELEASE }} 
          docker push ${{ secrets.DOCKER_USERNAME }}/hadoop-resourcemanager:${{ env.RELEASE }} 
          docker push ${{ secrets.DOCKER_USERNAME }}/hadoop-nodemanager:${{ env.RELEASE }} 
          docker push ${{ secrets.DOCKER_USERNAME }}/hadoop-historyserver:${{ env.RELEASE }} 
          docker push ${{ secrets.DOCKER_USERNAME }}/hadoop-submit:${{ env.RELEASE }}